# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- release/*

pool:
  # vmImage: ubuntu-latest
  vmImage: ubuntu-24.04

steps:
- task: NodeTool@0
  inputs:
    # versionSpec: '14.21.3'
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
    npm cache clean --force
    npm install -g @angular/cli@11.0.7
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(05fe7b95-570c-4eb2-b461-4796f80a4269)'
    appType: 'webApp'
    WebAppName: 'bernardomondragon'
    packageForLinux: 'dist/'