import { DOCUMENT } from '@angular/common';
import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute, NavigationEnd, Router } from '@angular/router';
import * as html2canvas from 'html2canvas';
import * as moment from 'moment';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-cv-root',
  templateUrl: './cv-root.component.html',
  styleUrls: ['./cv-root.component.scss']
})
export class CvRootComponent implements OnInit {
  showDynamicDisplayContent: boolean = false;
  name = 'Bernardo Mondragon Brozon';
  date = moment().format('MM/DD/YYYY');
  routeFragmentSubscription: Subscription | undefined;
  selectedTabIndex: number | undefined;

  // NgClass directive example
  isPurple = true;
  isBlue = false;

  // NgStyle directive example
  leftPanelFontColor = 'white';

  //#region CV Tab content
  experiences = [
    {
      logoUrl: '../../../../../assets/images/logos/Zurich.PNG',
      position: 'Senior Full-stack Developer',
      company: 'Zurich Insurance Company Ltd',
      employmentType: 'Full-time',
      startDate: '2020-11-01T00:00:00.000Z',
      endDate: null,
      location: 'Mexico City, Mexico',
      description: `
        <p>Full stack development of sureties administration system for Zurich North América.</p>
        <p>Financial Analysis and Underwriting automation.</p>
        <p>Technologies used: Blazor, .Net, Entity Framework, SQL Server, Bitbucket, Jira, Jfrog, Jenkins, Linux VMs, Figma.</p>
      `
    },
    {
      logoUrl: '../../../../../assets/images/logos/Kalyptio.png',
      position: 'Founding Partner',
      company: 'Kalyptio',
      employmentType: 'Part-time',
      startDate: '2019-01-01T00:00:00.000Z',
      endDate: null,
      location: 'Mexico City, Mexico',
      description: `
      <p>Design and execute strategic processes to deliver best quality software for our clients.</p>
      <p>I monitor that industry standards are met according to best coding practices.</p>
      <p>I have satisfied over 30+ customers providing them with software that suits their needs</p>
      `
    },
    {
      logoUrl: '../../../../../assets/images/logos/Kalyptio.png',
      position: 'Senior Full-stack Developer',
      company: 'Neolinx de Mexico',
      employmentType: 'Full-time',
      startDate: '2014-01-01T00:00:00.000Z',
      endDate: '2019-01-01T00:00:00.000Z',
      location: 'Mexico City, Mexico',
      description: `
      <p>Succesfully developed and implemented software solutions to manipulate and analyse data generated by the telecommunication industry for Mexico's Attorney-General's Office (PGR) and Mexico's Center of Investigation and Nation Security (CISEN).</p>
          <p>Helped saving hundreds of lives and preventing thousands of crimes.</p>
          <p>Succesfully parsed over 700 million CDR (call detail registries) from different random formats.</p>
      `
    },
    {
      logoUrl: '../../../../../assets/images/logos/Koomkin.PNG',
      position: 'Full-stack Developer',
      company: 'Grupo Koomkin',
      employmentType: 'Full-time',
      startDate: '2016-08-01T00:00:00.000Z',
      endDate: '2017-02-01T00:00:00.000Z',
      location: 'Mexico City, Mexico',
      description: `
      <p>Analyzed digital marketing campaigns data to maximize lead conversion rates for customers.</p>
          <p>Coded algorithms and designed UI UX flows for lead generation in digital platforms.</p>
          <p>Succesfully increased the lead convertion ratio for 40+ clients.</p>
      `
    },
    {
      logoUrl: '../../../../../assets/images/logos/Koomkin.PNG',
      position: 'Producer',
      company: 'Ecorise Youth Innovations',
      employmentType: 'Full-time',
      startDate: '2016-08-01T00:00:00.000Z',
      endDate: '2017-02-01T00:00:00.000Z',
      location: 'Austin, TX',
      description: `
      <p>Analyzed digital marketing campaigns data to maximize lead conversion rates for customers.</p>
          <p>Coded algorithms and designed UI UX flows for lead generation in digital platforms.</p>
          <p>Succesfully increased the lead convertion ratio for 40+ clients.</p>
      `
    }
  ];
  //#endregion

  // NgFor directive example
  // TODO: Fetch this information from database
  sections = [{
    title: 'Education',
    places: [{
      position: 'Bachelor\'s in Actuarial Science',
      startDate: new Date('08/01/2013'),
      endDate: new Date('08/01/2018'),
      place: 'Instituto Tecnologico Autonomo de Mexico (ITAM)',
      points: [
        'Applied mathematics and statistical methods to assess risk in insurance, finance and other industries and professions.'
      ]
    }]
  }, {
    title: 'Experience',
    places: [{
      position: 'CoFounder & Director',
      startDate: new Date('01/01/2019'),
      endDate: null,
      place: 'Kanto Studio, Mexico City',
      points: [
        'Design and execute strategic processes to deliver best quality software for our clients.',
        'I monitor that industry standards are met according to best coding practices.',
        'I have satisfied over 30+ customers providing them with software that suits their needs.'
      ]
    }, {
      position: 'Full-stack Developer',
      startDate: new Date('01/01/2014'),
      endDate: new Date('01/01/2018'),
      place: 'Neolinx de México SA. de CV., Mexico City',
      points: [
        'Succesfully developed and implemented software solutions to manipulate and analyse data generated by the telecommunication industry for Mexico\'s Attorney-General\'s Office (PGR) and Mexico\'s Center of Investigation and Nation Security (CISEN).',
        'Helped saving hundreds of lives and preventing thousands of crimes.',
        'Succesfully parsed over 700 million CDR (call detail registries) from different random formats.'
      ]
    }]
  }, {
    title: 'Achivements',
    places: [{
      position: 'Insurance product on IUD failure risk',
      startDate: new Date('05/01/2019'),
      endDate: null,
      place: 'Mexico City',
      points: [
        'Developed a model to asses and manage IUD (Intra Uterus Device) failure risk for an innovative insurance product placement.',
        'Succefully computed risk and market premiums, risk reserves, policy values, risk and utility margins and other actuarial measurements for the product under the Solvency II framework in order for it to be a viable and sustainable insurance product.'
      ]
    }]
  }];

  constructor(
    @Inject(DOCUMENT) private document: any,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.router.events.subscribe(event => {
      if (event instanceof NavigationEnd) {
        const fragment = event.url.split('#')[1];
        if (fragment) {
          return;
        }
        window.scrollTo(0, 0);
      }
      return;
    });

    // Set the current tab getting route fragment if any
    this.routeFragmentSubscription = this.route.fragment.subscribe((fragment: string) => {
      if (fragment) {
        switch (fragment) {
          case 'cv': 
            this.selectedTabIndex = 0;
            break;
          case 'resume':
            this.selectedTabIndex = 1;
            break;
          case 'activities': 
            this.selectedTabIndex = 2;
            break;
          default:
            this.selectedTabIndex = 0;
            break;
        }
      }
    });
  }

  ngOnInit(): void {
  }

  onTabNavigation(tabIndex: number) {
    const fragments = ['cv', 'resume', 'activities'];
    this.router.navigate(['./'], {
      fragment: fragments[tabIndex],
      relativeTo: this.route,
      replaceUrl: true
    });
  }

  changeLeftPanelStyle(color: string): void {
    switch (color) {
      case 'purple':
        this.isPurple = true; this.isBlue = false; this.leftPanelFontColor = 'white';
        break;
      case 'blue':
        this.isPurple = false; this.isBlue = true; this.leftPanelFontColor = 'white';
        break;
      case 'gray':
        this.isPurple = false; this.isBlue = false; this.leftPanelFontColor = 'black';
        break;
      default: // Optional
        // purple case
        this.isPurple = true; this.isBlue = false; this.leftPanelFontColor = 'white';
        break;
    }
  }

  getDuration(startDate: any, endDate: any) {
    const durationEndDate = endDate != null ? endDate : new Date();
    const start = moment(startDate);
    const end = moment(durationEndDate);
    const duration = moment.duration(start.diff(end)).humanize();
    return duration;
  }

  async downloadResume() {
    this.document.getElementById('html-element').style.scrollBehavior = 'unset';
    window.scrollTo(0, 0);
    setTimeout(async () => {
      let element: HTMLElement;
      element = <HTMLElement>(document.querySelector('#document'));
      const canvas = await html2canvas.default(element);
      /* document.body.appendChild(canvas); */
      const contentDataURL = canvas.toDataURL('image/png');
      const download = document.createElement('a');
      download.href = contentDataURL;
      download.download = ``;
      download.click();
      this.document.getElementById('html-element').style.scrollBehavior = 'smooth';
    }, 1);
  }

  async downloadResumeZip() {
    window.open(`/assets/Resume Bernardo Mondragon.zip`);
  }

}
